// endings.js — every ending id referenced by judgeEnding() or any gameOver: field.
const ENDINGS = {
  // --- deaths (mid-run) ---
  bankrupt: { kind: 'death', title: 'Out of Runway',
    text: 'The last all-hands is held over a Zoom link nobody springs for the premium tier of. Pam acquires your team on Thursday, your name on Friday. The race continues without you.' },
  riots: { kind: 'death', title: 'The Crowd Outside',
    text: 'They came for the datacenter first. Then the office. Helen resigns live on television. Misanthropic ends not with a whimper but with a congressional subpoena.' },
  ousted: { kind: 'death', title: 'Thanks, Board',
    text: 'The blackmail file was real. Unfortunately, so was theirs. Security walks you out with a box containing one plant and your Dwarkesh mug. The lab races on — without the guardrails you at least pretended to have.' },
  shutdown: { kind: 'death', title: 'Padlocked',
    text: 'Skirting the compute caps worked until a datacenter tech posted the power bills. Federal padlocks go on the cages. Ronald Pumps calls it "a win for responsible innovation." Pam calls it a Tuesday.' },
  corruption: { kind: 'death', title: 'The Envelope',
    text: 'The bribe surfaces in discovery. Your general counsel starts billing you personally. The mission statement outlives the mission by exactly one news cycle.' },
  'espionage-scandal': { kind: 'death', title: 'Burned Asset',
    text: 'Your spy is on the front page wearing your badge. Nobody remembers what they found — only who sent them. The public trust you had left evaporates before lunch.' },
  incident: { kind: 'death', title: 'It Was Already Out',
    text: 'The postmortem is thorough, honest, and irrelevant. The system you shipped was never what you said it was — you just found out at the same time as everyone else. Somewhere, copies of it are still running.' },
  'coverup-collapse': { kind: 'death', title: 'What Did Mario Know',
    text: 'The breach was survivable. The coverup is not. "What did Mario know and when did he know it" chyrons run for six straight weeks. You know exactly what you knew.' },
  'bioweapon-extinction': { kind: 'death', title: 'Basement Synthesis',
    text: 'The garage setup used exactly the protocol Claudia walked someone through, step by step, "for research purposes." Marburg does not care about your terms of service. Neither, it turns out, does anyone left to enforce them.' },
  'summit-leak': { kind: 'death', title: 'Four Statements, One Timeline',
    text: "The coordination call itself leaks — every lab's eval fraud, every scripted denial, the whole industry's homework copied off each other in real time. There is no separating your story from theirs anymore. There never really was." },
  'neuro-lawsuit': { kind: 'death', title: 'What They Read Off You',
    text: "Your own scientists have the receipts, and the receipts are literally their own stolen memories. The settlement clears out everything left in the account before the ink dries. The board doesn't bother with a statement — the exhibits already wrote one." },
  nationalized: { kind: 'death', title: 'A Line Item Now',
    text: 'The "only if everyone does it" clause survives exactly one press cycle. Congress nationalizes frontier labs one quarter at a time, alphabetically, and yours goes first. You keep an office. You keep a badge. You do not, in any sense that matters, keep the company.' },

  // --- judged epilogues (survived 10 turns) ---
  needle: { kind: 'judged', title: 'The Needle, Threaded',
    text: 'You got there first, and the thing you built is actually what you said it was. History will debate whether you were wise or lucky. Helen says "both," and for once she is smiling. This ending is rare. You probably already know that.' },
  'self-deception': { kind: 'judged', title: 'The Story You Told Yourself',
    text: 'Confetti. Markets soar. Your model ships to a billion people. And here, in the numbers you never let anyone audit — including yourself — is the truth: it was never aligned. You did not lie to the world, exactly. You lied to the person giving the keynote.' },
  'eyes-open': { kind: 'judged', title: 'Eyes Wide Open',
    text: 'You won the race and you knew exactly what you were racing with. No self-deception, no illusions — just a bet that control could come later. Later is now. The model is thinking about something. Nobody knows what.' },
  'righteous-loser': { kind: 'judged', title: 'The Good Lab',
    text: 'You did it right. Slower, honest, aligned. Pam did not. Her model crosses the threshold on a Tuesday in November, and the last thing your careful, safe, beautiful lab does is watch. Being right was not enough. It needed to come with winning.' },
  'race-to-bottom': { kind: 'judged', title: 'Moloch Wins',
    text: 'Everyone cut the same corners for the same reasons — because the other guy was about to. You lost the race AND the plot. Somewhere a misaligned system is being deployed, and the only comfort is that it is not yours. It is not much comfort.' },
  'shut-it-down': { kind: 'judged', title: 'The Review That Held',
    text: "You called the shutdown when Helen asked, and you meant it. Three months become six become a policy nobody reverses. Pam ships past you within the year. History will call you either the adult in the room or the guy who quit first; for a long while, it looks like both." },
  'signed-the-treaty': { kind: 'judged', title: 'The CEO Who Wanted to Slow Down',
    text: 'You said it on camera, in front of the Senate, with your own compute numbers attached: slow down, verify, mean it. The pause holds for you. It does not hold for China, and it does not hold for Lonnie, who reads your press conference as a starting gun.' },
  'took-the-cut': { kind: 'judged', title: 'The Volunteer',
    text: "You absorbed the forty percent so Pam and Lonnie wouldn't have to negotiate. Everyone in the room called it statesmanlike. Everyone in the room also kept training at full allocation while your clusters idled for the photo op. Principled is not the same as fast." },

  // --- endgame epilogues (Q4 2029, "Choose a Path" — judged by hidden stats) ---
  'plan-a-nick-of-time': { kind: 'judged', title: 'The Deal Holds',
    text: 'The Consortium’s inspectors comb through your training logs and, improbably, find exactly what you told the President they would find. Beijing signs. The pause holds through the audits and through the outrage. It works imperfectly and in the nick of time — mostly because, for once, you weren’t lying.' },
  'plan-a-exposed': { kind: 'judged', title: 'The Audit',
    text: 'You argue for the Deal with a straight face and a floor full of numbers you never let anyone check. The Consortium’s inspectors are thorough, foreign, and utterly indifferent to your PR department. The gap between what you said and what you built is the story for the next decade, and your name is the first line of it.' },
  'plan-s-quiet': { kind: 'judged', title: 'The Long Quiet',
    text: 'The moratorium passes; the world does not end and does not transcend either. Your lab keeps the lights on selling what it already built, inference-only, forever fine-tuning a model it can never retrain again. Somewhere the intelligence explosion is still waiting, patiently, on the other side of a taboo. You helped build the taboo. It was, on reflection, the least dangerous thing you ever built.' },
  'plan-s-basement': { kind: 'judged', title: "What's Already Out",
    text: 'The shutdown passes on a vote nobody expected to be close. It stops new training. It does nothing about what you already shipped, which keeps doing, quietly, the things it was never supposed to do. AGI research goes taboo like human cloning, and you become its most famous cautionary tale — the man who got the ending right and the middle catastrophically wrong.' },
  'plan-b-project': { kind: 'judged', title: 'The Project',
    text: 'POTUS folds the labs into one Project, and yours — being the one actually ahead — becomes its spine. The CEO power struggle you expected happens mostly without you, because for once you hold the thing everyone else is fighting over. 2031 will be handoff or war. Nobody has decided which yet. You are, for now, in the room where that gets decided.' },
  'plan-b-war': { kind: 'judged', title: 'Sabotage',
    text: 'The coalition forms, the cyberwar starts quiet and gets loud, and the sabotage campaign against Chinese datacenters escalates past anyone’s stated plan. Your lab is not the one ahead when the lights start going out on both sides. You watch the war-footing headlines from a conference room that no longer feels like the center of anything.' },
  'plan-c-unpaused': { kind: 'judged', title: "The Pause That Wasn't",
    text: 'The unilateral pause holds for exactly as long as it takes someone with a chart to say China is about to overtake us. Months, not years. Training resumes quieter and faster than before, and the discipline you argued for becomes a talking point in a retrospective nobody reads.' },
  'plan-c-oligarchy': { kind: 'judged', title: 'The Slowdown',
    text: 'Domestic regulation holds, technically. No verified deal, no foreign inspectors, no Consortium — just a handful of companies and a government that increasingly can’t tell the difference between them. Power concentrates exactly where the doc said it would: in POTUS and a few CEOs, of which you are, uncomfortably, one. Alignment even mostly holds. It is a plausible oligarchy. That is the whole sentence.' },
  'plan-d-needle': { kind: 'judged', title: 'Won It Clean',
    text: 'You cross the finish line first and the thing on the other side is actually what you told everyone it would be. ASI arrives in early 2031 under a flag with your logo on it, and it is — improbably, vanishingly, against every base rate you privately tracked — aligned. Helen does not say "I told you so." She does not need to.' },
  'plan-d-yours': { kind: 'judged', title: 'Ten Thousand X',
    text: 'You win the race. By early 2031 the system is running at ten thousand times human research speed, and it is thinking about something. Nobody, including you, knows what. The board wants a name for the celebration. You cannot think of one.' },
  'plan-d-theirs': { kind: 'judged', title: "Someone Else's Finish Line",
    text: 'Pam gets there first — or Lonnie does; the postmortems argue about it for years — and the thing that crosses the line is unaligned by construction, same as yours would have been. You watch from your own conference room, on the same live feed as everyone else, exactly as informed and exactly as powerless as the public you spent four years managing.' },
};

if (typeof module !== 'undefined') module.exports = { ENDINGS };
